language: php
php:
  - 7.2
before_install:
  - composer install

script:
  - mkdir -p tests/logs
  - ./vendor/bin/phpunit --coverage-clover tests/logs/clover.xml --coverage-html tests/logs/clover_html *Test.php

after_success:
  - travis_retry php ./vendor/bin/php-coveralls -v
