language: php
php:
  - 7.2.32
before_install:
- composer install --dev

script:
- ./vendor/bin/phpunit --coverage-clover tests/logs/clover.xml --coverage-html tests/logs/clover_html tests/

after_script:
- php vendor/bin/coveralls -v